import { Box, Heading, Text } from '@chakra-ui/react'
import Head from 'next/head'

import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next.js Template.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box p={4}>
          <Heading marginBottom={2}>hello, world!</Heading>
          <Text fontSize='md' background={"blue.700"} textColor={'white'}>This is Next.js starter template.</Text>
        </Box>
      </main>
    </>
  )
}

export default Home
